name: Batch keybox checker
description: Batch keybox checker
inputs:
  path:
    description: directory where keybox is located, defaults to current directory.
    required: false
    default: "."
runs:
  using: 'composite'
  steps:
    - run: pip install "${{ github.action_path }}"
      shell: bash
    - run: keyboxchecker "${{ inputs.path }}"
      shell: bash
      env:
        repository: "${{ github.repository }}"
        action_repository: "${{ github.action_repository }}"
