name: Batch keybox checker
description: Batch keybox checker
inputs:
  aosp:
    description: A boolean value that categorizes the AOSP keybox as a survivor, defaulting to False.
    required: false
    default: false
  output:
    description: Directory where keybox is located, defaults to current directory.
    required: false
    default: "."
  path:
    description: Directory where keybox is located, defaults to current directory.
    required: false
    default: "."
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
  
    - run: pip install "${{ github.action_path }}"
      shell: bash
    
    - if: ${{ inputs.aosp != 'false' }}
      run: keyboxchecker -a -p "${{ inputs.path }}" -o "${{ inputs.output }}"
      shell: bash
      env:
        repository: "${{ github.repository }}"
        action_repository: "${{ github.action_repository }}"
    
    - if: ${{ inputs.aosp == 'false' }}
      run: keyboxchecker -p "${{ inputs.path }}" -o "${{ inputs.output }}"
      shell: bash
      env:
        repository: "${{ github.repository }}"
        action_repository: "${{ github.action_repository }}"
