name: Batch keybox checker
description: Batch keybox checker
runs:
  using: 'composite'
  steps:
    - run: pip install ${{ github.action_path }}
      shell: bash
    - run: keyboxchecker
      shell: bash
