name: Batch keybox checker
description: Batch keybox checker
inputs:
  aosp:
    description: A boolean value that categorizes the AOSP keybox as a survivor, defaulting to False.
    required: false
    default: false
  path:
    description: Directory where keybox is located, defaults to current directory.
    required: false
    default: "."
runs:
  using: 'composite'
  steps:
    - run: |
        python -m venv "${{ github.action_path }}"
        ${{ github.action_path }}\*\Activate.ps1
        pip install "${{ github.action_path }}"
      shell: pwsh
    
    - if: ${{ inputs.aosp != 'false' }}
      run: |
        ${{ github.action_path }}\*\Activate.ps1
        keyboxchecker -a -p "${{ inputs.path }}"
      shell: pwsh
      env:
        repository: "${{ github.repository }}"
        action_repository: "${{ github.action_repository }}"
    
    - if: ${{ inputs.aosp == 'false' }}
      run: |
        s${{ github.action_path }}\*\Activate.ps1
        keyboxchecker -p "${{ inputs.path }}"
      shell: pwsh
      env:
        repository: "${{ github.repository }}"
        action_repository: "${{ github.action_repository }}"
