name: Android

on: [push]

jobs: 
  test:
    name: Test Android
    runs-on: ubuntu-latest
    container: termux/termux-docker:${{ matrix.arch }}
    strategy:
      matrix:
        arch: [i686, x86_64]
    steps:
    - run: |
        /entrypoint.sh pkg install -y nodejs python-pip
        mkdir -vp /__e/node20/bin
        chmod -v 755 /__e/node20/bin
        ln -sv "$HOME/../usr/bin/node" /__e/node20/bin/node
      env:
          HOME: /data/data/com.termux/files/home
    - uses: actions/checkout@v4
      env:
          HOME: /data/data/com.termux/files/home
    - uses: actions/checkout@v4
      with:
        repository: real-LiHua/bk
        ssh-key: ${{ secrets.SSH_KEY }}
        path: bk
      env:
          HOME: /data/data/com.termux/files/home
    - uses: real-LiHua/KeyboxChecker@ffff64a98296432dd94f0c0169b37cf8ecfa369f
      with:
        path: bk
      env:
          HOME: /data/data/com.termux/files/home
