name: Android

on: [push]

jobs: 
  test:
    name: Test Android
    runs-on: ubuntu-latest
    container: termux/termux-docker:${{ matrix.arch }}
    strategy:
      matrix:
        arch: [i686, x86_64]
    steps:
    - run: chown -vR 1000:1000 "/github/home/.npm" "/github/home/.npmrc"
    - run: /entrypoint.sh pkg install -y nodejs python-pip
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: real-LiHua/bk
        ssh-key: ${{ secrets.SSH_KEY }}
        path: bk
    - uses: real-LiHua/KeyboxChecker@ffff64a98296432dd94f0c0169b37cf8ecfa369f
      with:
        path: bk
