name: Android

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/android.yml"

jobs: 
  test:
    name: Test Android
    runs-on: ubuntu-latest
    container: termux/termux-docker:${{ matrix.arch }}
    strategy:
      matrix:
        arch: [i686, x86_64]
    defaults:
      run:
        working-directory: /data/data/com.termux/files/home
    steps:
    - run: /entrypoint.sh pkg install -y git openssh python-pip rust
      env:
          HOME: /data/data/com.termux/files/home
    - run: |
        echo "${{ secrets.SSH_KEY }}" > .ssh/id_ed25519
        echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" > .ssh/known_hosts
        chmod -v 600 .ssh/id_ed25519
        chmod -v 600 .ssh/known_hosts
        chown -vR 1000:1000 .ssh
    - run: |
        /entrypoint.sh git clone git@github.com:real-LiHua/bk "$HOME/bk"
        /entrypoint.sh python -m venv "$HOME"
        export PATH="$HOME/bin:/data/data/com.termux/files/usr/bin:$PATH"
        /entrypoint.sh VIRTUAL_ENV="$HOME" pip install git+https://github.com/real-LiHua/KeyboxChecker
        /entrypoint.sh VIRTUAL_ENV="$HOME" 'cd;keyboxchecker bk'
      env:
          HOME: /data/data/com.termux/files/home
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_ed25519"
