name: Check

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/check.yml"

jobs: 
  check:
    name: Setup ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - run: pip install .
        
    - name: Black
      if: ${{ runner.os == 'linux' }}
      uses: microsoft/action-python@0.7.3
      with:
        black: true
        workdir: "."

    - name: Bandit
      uses: microsoft/action-python@0.7.3
      with:          
        bandit: true

    
    - name: Pylint
      if: ${{ runner.os == 'linux' }}
      uses: microsoft/action-python@0.7.3
      with:          
        pylint: true
        workdir: "."
        python_version:  ${{ matrix.python-version }}
        
    - name: Pyright
      uses: microsoft/action-python@0.7.3
      with:          
        pyright: true
        workdir: "."
          
    - name: Flake8
      if: ${{ runner.os != 'windows' }}
      uses: microsoft/action-python@0.7.3
      with:          
        flake8: true
        workdir: "."
