name: check

on: [push]

jobs: 
  pylint:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - run: pip install .
        
    - name: Black
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      uses: microsoft/action-python@0.7.0
      with:
        black: true
        workdir: "."

    - name: Bandit
      uses: microsoft/action-python@0.7.0
      with:          
        bandit: true
          
    - name: Pyright
      uses: microsoft/action-python@0.7.0
      with:          
        pyright: true
        workdir: "."
          
    - name: Flake8
      if: ${{ ! startsWith(matrix.os, 'windows') }}
      uses: microsoft/action-python@0.7.0
      with:          
        flake8: true
        workdir: "."
