name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      discussions: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build package
        run: |
          python -m venv .
          source bin/activate
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*.whl"
          generate_release_notes: true
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.10.2
