name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: pip wheel --no-deps .
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.whl"
          generate_release_notes: true
