name: Test

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/test.yml"

jobs: 
  test:
    name: Test ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: real-LiHua/bk
        ssh-key: ${{ secrets.SSH_KEY }}
        
    - run: git checkout -b ${{ matrix.os }}-${{ matrix.python }}
    
    - uses: real-LiHua/KeyboxChecker@main
        
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        branch: ${{ matrix.os }}
        ssh-key: ${{ secrets.SSH_KEY }}
        push_options: '--force'
