name: Test

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/test.yml"

jobs: 
  test:
    name: Test ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: real-LiHua/bk
        ssh-key: ${{ secrets.SSH_KEY }}
        
    - run: git checkout -b ${{ matrix.os }}-${{ matrix.python }}
    
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - uses: real-LiHua/KeyboxChecker@fb4378f4d8f603591f819c20fe0c18a1aad431c7
        
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: ${{ matrix.os }}-${{ matrix.python }}
        ssh-key: ${{ secrets.SSH_KEY }}
        push_options: '--force'
