name: Test

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/test.yml"

jobs: 
  test:
    name: Test ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04, ubuntu-22.04]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: real-LiHua/bk
        ssh-key: ${{ secrets.SSH_KEY }}
        path: bk
    
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: real-LiHua/KeyboxChecker@35b51140390ac1dbdd048832fd9c8da37a679b9b
      with:
        path: bk
